### ISSUE TITLE
m3u8

### ISSUE THREAD

**Issue by arty777** [whatvn/ngx_http_estreaming_module#18]
in config 
segment_length 5;
in playlist i see
# EXTM3U
# EXT-X-TARGETDURATION:8
# EXT-X-MEDIA-SEQUENCE:0
# EXT-X-VERSION:4
# EXTINF:10.010,

how to understant than chunk size 5 sec?

**Comment by whatvn** [comment]
the segment length is right or wrong base on your video file. 
if you convert your video using following command, I believe the segment length will be correct. 

``` bash
ffmpeg -y -i video.mp4 -codec:v libx264 -profile:v baseline -level 3.0 -preset medium -threads 0 -aspect 16:9 -r 30.000  -b:v 1000k -maxrate 887k -bufsize 960k -s 854x480 -ar 44100 -g 30.000 -keyint_min 60                           -x264opts "bframes=16:keyint=50:min-keyint=50:no-scenecut"  -c:a libfdk_aac -b:a 128k output.mp4
```

**Comment by arty777** [comment]
i use handbrake for convert videofiles 

and how to understand is everything is fine with segment length? 

It turns out that the configuration parameter does not mean anything and everything depends on the videofile?

#EXTINF:10.010,
0/101.ts?secl=BLQ0nVRzPskrjS63BLT4EQ&sect=1442430092
#EXTINF:9.135,
1/101.ts?secl=BLQ0nVRzPskrjS63BLT4EQ&sect=1442430092
#EXTINF:9.927,
......
9/101.ts?secl=BLQ0nVRzPskrjS63BLT4EQ&sect=1442430092
#EXTINF:10.011,
10/101.ts?secl=BLQ0nVRzPskrjS63BLT4EQ&sect=1442430092
#EXTINF:10.010,
11/101.ts?secl=BLQ0nVRzPskrjS63BLT4EQ&sect=1442430092
#EXTINF:10.011,

what mean #EXTINF:10.011,?

**Comment by whatvn** [comment]
The EXTINF tag specifies the duration of a media segment, estreaming module will try to split your video into to small chunks with configured segment length, if and only if your video has keyframe setting, bitrate control and other h264 parameters right.

In order to do this, you have to learn how to use ffmpeg (or handbrake) the right way. 
For example, with my video file, convert using above command, if segment_length is 3, the output should be like this:

``` bash
EXTM3U
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-VERSION:4
#EXTINF:3.334,
0/206346.ts
#EXTINF:3.334,
2/206346.ts
#EXTINF:3.334,
4/206346.ts
#EXTINF:3.334,
6/206346.ts
#EXTINF:3.334,
8/206346.ts
#EXTINF:3.334,
10/206346.ts
#EXTINF:3.334,
...
```

and when I set it to 5, it will be:

``` bash
curl http://s1.videofly.vn/2015/09/16/adbr/360p/206346.m3u8
#EXTM3U
#EXT-X-TARGETDURATION:8
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-VERSION:4
#EXTINF:5.001,
0/206346.ts
#EXTINF:5.001,
3/206346.ts
#EXTINF:5.001,
6/206346.ts
#EXTINF:5.001,
9/206346.ts
#EXTINF:5.001,
12/206346.ts
#EXTINF:5.001,
15/206346.ts
#EXTINF:5.001,
18/206346.ts
#EXTINF:5.001,
21/206346.ts
#EXTINF:5.001,
24/206346.ts
#EXTINF:5.001,
27/206346.ts
#EXTINF:5.001,
30/206346.ts
#EXTINF:5.001,
....
```

You should read: 
http://www.streaminglearningcenter.com/articles/how-to-encode-video-for-hls-delivery.html
http://streaminglearningcenter.com/articles/encoding-for-adaptive-streaming-3.html
